# Generated by Django 4.1.7 on 2023-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
